In [2]:
import pandas as pd

1. Load the dataset.

In [ ]:
df = pd.read_csv('googleplaystore.csv')

2. Display the first 5 rows.

In [6]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

3. Display the last 5 rows

In [7]:
df.tail()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

4. Check dataset structure and non-null values

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 2.2 MB

5. Summary statistics for all columns

In [9]:
df.describe(include="all")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
count,10841,10841,9367.000000,10841,10841,10841,10840,10841,10840,10841,10841,10833,10838
unique,9660,34,NaN,6002,462,22,3,93,6,120,1378,2832,33
top,ROBLOX,FAMILY,NaN,0,Varies with device,"1,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,4.1 and up
freq,9,1972,NaN,596,1695,1579,10039,10040,8714,842,326,1459,2451
mean,NaN,NaN,4.193338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.537431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

6. Display column names and data types

In [10]:
print(df.columns)
print(df.dtypes)

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')
App                   str
Category              str
Rating            float64
Reviews               str
Size                  str
Installs              str
Type                  str
Price                 str
Content Rating        str
Genres                str
Last Updated          str
Current Ver           str
Android Ver           str
dtype: object

7. Identify missing values in each column

In [11]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

8. Remove rows where Rating is missing

In [12]:
df = df.dropna(subset=["Rating"])

9. Fill missing values in Type with the most frequent value

In [13]:
df["Type"] = df["Type"].fillna(df["Type"].mode()[0])

10. Remove duplicate records

In [14]:
df = df.drop_duplicates()

11. Clean Installs and convert to numeric

In [15]:
df["Installs"] = df["Installs"].str.replace("+", "", regex=False)
df["Installs"] = df["Installs"].str.replace(",", "", regex=False)

df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

12. Clean Price and convert to numeric

In [16]:
df["Price"] = df["Price"].str.replace("$", "", regex=False)

df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

13. Convert Reviews to integer

In [17]:
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

df = df.dropna(subset=["Reviews"])

df["Reviews"] = df["Reviews"].astype(int)

14. Convert Last Updated to datetime

In [18]:
df["Last Updated"] = pd.to_datetime(
    df["Last Updated"],
    errors="coerce"
)

15. Convert all app names to lowercase

In [19]:
df["App"] = df["App"].str.lower()

16. Convert Category names to uppercase

In [20]:
df["Category"] = df["Category"].str.upper()

17. Split Genres into multiple parts

In [21]:
df["Genres"].str.split(";")

0                      [Art & Design]
1        [Art & Design, Pretend Play]
2                      [Art & Design]
3                      [Art & Design]
4          [Art & Design, Creativity]
                     ...
10834                     [Education]
10836                     [Education]
10837                     [Education]
10839             [Books & Reference]
10840                     [Lifestyle]
Name: Genres, Length: 8892, dtype: object

18. Replace unwanted text patterns in Category

In [22]:
df["Category"] = df["Category"].str.replace("_", " ", regex=False)

19. Filter apps with Rating > 4.5

In [23]:
high_rating_apps = df[df["Rating"] > 4.5]

high_rating_apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
9,kids paint free - drawing fun,ART AND DESIGN,4.7,121,3.1M,10000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-07-03,2.8,4.0.3 and up
13,mandala coloring book,ART AND DESIGN,4.6,4326,21M,100000.0,Free,0.0,Everyone,Art & Design,2018-06-26,1.0.4,4.4 and up
16,photo designer - write your name with shapes,ART AND DESIGN,4.7,3632,5.5M,500000.0,Free,0.0,Everyone,Art & Design,2018-07-31,3.1,4.1 and up
19,ibis paint x,ART AND DESIGN,4.6,224399,31M,10000000.0,Free,0.0,Everyone,Art & Design,2018-07-30,5.5.4,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10810,fr lupupa sermons,BUSINESS,4.8,19,21M,100.0,Free,0.0,Everyone,Business,2018-06-12,1.0,4.4 and up
10820,fr. daoud lamei,FAMILY,5.0,22,8.6M,1000.0,Free,0.0,Teen,Education,2018-06-27,3.8.0,4.1 and up
10829,bulgarian french dictionary fr,BOOKS AND REFERENCE,4.6,603,7.4M,10000.0,Free,0.0,Everyone,Books & Reference,2016-06-19,2.96,4.1 and up
10833,chemin (fr),BOOKS AND REFERENCE,4.8,44,619k,1000.0,Free,0.0,Everyone,Books & Reference,2014-03-23,0.8,2.2 and up
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100.0,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up

20. Find all free apps

In [24]:
free_apps = df[df["Price"] == 0]

free_apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,fr calculator,FAMILY,4.0,7,2.6M,500.0,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5000.0,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100.0,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up
10839,the scp foundation db fr nn5n,BOOKS AND REFERENCE,4.5,114,Varies with device,1000.0,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000.0,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device

21. Apps with more than 1,000,000 installs

In [25]:
popular_apps = df[df["Installs"] > 1000000]

popular_apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up
12,tattoo name on my photo editor,ART AND DESIGN,4.2,44829,20M,10000000.0,Free,0.0,Teen,Art & Design,2018-04-02,3.8,4.1 and up
18,flipaclip - cartoon animation,ART AND DESIGN,4.3,194216,39M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-03,2.2.5,4.0.3 and up
19,ibis paint x,ART AND DESIGN,4.6,224399,31M,10000000.0,Free,0.0,Everyone,Art & Design,2018-07-30,5.5.4,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10740,photofunia,PHOTOGRAPHY,4.3,316378,4.4M,10000000.0,Free,0.0,Everyone,Photography,2017-06-03,4.0.7.0,2.3 and up
10781,modern strike online,GAME,4.3,834117,44M,10000000.0,Free,0.0,Teen,Action,2018-07-30,1.25.4,4.1 and up
10784,big hunter,GAME,4.3,245455,84M,10000000.0,Free,0.0,Everyone 10+,Action,2018-05-31,2.8.6,4.0 and up
10826,frim: get new friends on local chat rooms,SOCIAL,4.0,88486,Varies with device,5000000.0,Free,0.0,Mature 17+,Social,2018-03-23,Varies with device,Varies with device
10840,ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19M,10000000.0,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device

22. Select apps belonging to multiple categories

In [26]:
selected_apps = df[
    df["Category"].isin(
        ["GAME", "FAMILY", "TOOLS"]
    )
]

selected_apps

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1653,roblox,GAME,4.5,4447388,67M,1.000000e+08,Free,0.0,Everyone 10+,Adventure;Action & Adventure,2018-07-31,2.347.225742,4.1 and up
1654,subway surfers,GAME,4.5,27722264,76M,1.000000e+09,Free,0.0,Everyone 10+,Arcade,2018-07-12,1.90.0,4.1 and up
1655,candy crush saga,GAME,4.4,22426677,74M,5.000000e+08,Free,0.0,Everyone,Casual,2018-07-05,1.129.0.2,4.1 and up
1656,solitaire,GAME,4.7,254258,23M,1.000000e+07,Free,0.0,Everyone,Card,2018-08-01,2.137.0,4.1 and up
1657,bubble shooter,GAME,4.5,148897,46M,1.000000e+07,Free,0.0,Everyone,Casual,2018-07-17,1.20.1,4.0.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10820,fr. daoud lamei,FAMILY,5.0,22,8.6M,1.000000e+03,Free,0.0,Teen,Education,2018-06-27,3.8.0,4.1 and up
10827,fr agnel ambarnath,FAMILY,4.2,117,13M,5.000000e+03,Free,0.0,Everyone,Education,2018-06-13,2.0.20,4.0.3 and up
10834,fr calculator,FAMILY,4.0,7,2.6M,5.000000e+02,Free,0.0,Everyone,Education,2017-06-18,1.0.0,4.1 and up
10836,sya9a maroc - fr,FAMILY,4.5,38,53M,5.000000e+03,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,1.000000e+02,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up

23. Filtering using query()

In [27]:
df.query("Rating > 4.5")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up
9,kids paint free - drawing fun,ART AND DESIGN,4.7,121,3.1M,10000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-07-03,2.8,4.0.3 and up
13,mandala coloring book,ART AND DESIGN,4.6,4326,21M,100000.0,Free,0.0,Everyone,Art & Design,2018-06-26,1.0.4,4.4 and up
16,photo designer - write your name with shapes,ART AND DESIGN,4.7,3632,5.5M,500000.0,Free,0.0,Everyone,Art & Design,2018-07-31,3.1,4.1 and up
19,ibis paint x,ART AND DESIGN,4.6,224399,31M,10000000.0,Free,0.0,Everyone,Art & Design,2018-07-30,5.5.4,4.1 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10810,fr lupupa sermons,BUSINESS,4.8,19,21M,100.0,Free,0.0,Everyone,Business,2018-06-12,1.0,4.4 and up
10820,fr. daoud lamei,FAMILY,5.0,22,8.6M,1000.0,Free,0.0,Teen,Education,2018-06-27,3.8.0,4.1 and up
10829,bulgarian french dictionary fr,BOOKS AND REFERENCE,4.6,603,7.4M,10000.0,Free,0.0,Everyone,Books & Reference,2016-06-19,2.96,4.1 and up
10833,chemin (fr),BOOKS AND REFERENCE,4.8,44,619k,1000.0,Free,0.0,Everyone,Books & Reference,2014-03-23,0.8,2.2 and up
10837,fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6M,100.0,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up

24. Create Revenue column

In [28]:
df["Revenue"] = df["Installs"] * df["Price"]

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,0.0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,0.0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,0.0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,0.0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,0.0

25. Create Rating Groups: Low, Medium, High

In [29]:
df["Rating_Group"] = pd.cut(
    df["Rating"],
    bins=[0, 3, 4, 5],
    labels=["Low", "Medium", "High"]
)

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,0.0,High
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,0.0,Medium
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,0.0,High
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,0.0,High
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,0.0,High

26. Flag high-install apps (>1 million)

In [30]:
df["High_Install"] = df["Installs"].apply(
    lambda x: 1 if x > 1000000 else 0
)

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,0.0,High,0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,0.0,Medium,0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,0.0,High,1
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,0.0,High,1
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,0.0,High,0

27. Convert Type into numeric values

In [31]:
df["Type_Numeric"] = df["Type"].map(
    {
        "Free": 0,
        "Paid": 1
    }
)

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install,Type_Numeric
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,0.0,High,0,0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,0.0,Medium,0,0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,0.0,High,1,0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,0.0,High,1,0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,0.0,High,0,0

In [32]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install,Type_Numeric
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,0.0,High,0,0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,0.0,Medium,0,0
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,0.0,High,1,0
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,0.0,High,1,0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,0.0,High,0,0

28. Sort apps by installs in descending order

In [33]:
df.sort_values(
    by="Installs",
    ascending=False
)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install,Type_Numeric
3896,subway surfers,GAME,4.5,27711703,76M,1.000000e+09,Free,0.00,Everyone 10+,Arcade,2018-07-12,1.90.0,4.1 and up,0.00,High,1,0
4153,hangouts,COMMUNICATION,4.0,3419464,Varies with device,1.000000e+09,Free,0.00,Everyone,Communication,2018-07-21,Varies with device,Varies with device,0.00,Medium,1,0
4150,google,TOOLS,4.4,8021623,Varies with device,1.000000e+09,Free,0.00,Everyone,Tools,2018-08-03,Varies with device,Varies with device,0.00,High,1,0
3904,whatsapp messenger,COMMUNICATION,4.4,69109672,Varies with device,1.000000e+09,Free,0.00,Everyone,Communication,2018-08-03,Varies with device,Varies with device,0.00,High,1,0
3816,google news,NEWS AND MAGAZINES,3.9,877643,13M,1.000000e+09,Free,0.00,Teen,News & Magazines,2018-08-01,5.2.0,4.4 and up,0.00,Medium,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2450,tablet reminder,MEDICAL,5.0,4,2.5M,5.000000e+00,Free,0.00,Everyone,Medical,2018-08-03,1.0,4.1 and up,0.00,High,0,0
2459,anatomy & physiology vocabulary exam review app,MEDICAL,5.0,1,4.6M,5.000000e+00,Free,0.00,Everyone,Medical,2018-08-02,2.0,4.0 and up,0.00,High,0,0
5917,ra ga ba,GAME,5.0,2,20M,1.000000e+00,Paid,1.49,Everyone,Arcade,2017-02-08,1.0.4,2.3 and up,1.49,High,0,1
2454,kba-ez health guide,MEDICAL,5.0,4,25M,1.000000e+00,Free,0.00,Everyone,Medical,2018-08-02,1.0.72,4.0.3 and up,0.00,High,0,0
10697,mu.f.o.,GAME,5.0,2,16M,1.000000e+00,Paid,0.99,Everyone,Arcade,2017-03-03,1.0,2.3 and up,0.99,High,0,1

29. Top 10 apps based on Reviews

In [34]:
df.nlargest(10, "Reviews")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install,Type_Numeric
2544,facebook,SOCIAL,4.1,78158306,Varies with device,1.000000e+09,Free,0.0,Teen,Social,2018-08-03,Varies with device,Varies with device,0.0,High,1,0
3943,facebook,SOCIAL,4.1,78128208,Varies with device,1.000000e+09,Free,0.0,Teen,Social,2018-08-03,Varies with device,Varies with device,0.0,High,1,0
336,whatsapp messenger,COMMUNICATION,4.4,69119316,Varies with device,1.000000e+09,Free,0.0,Everyone,Communication,2018-08-03,Varies with device,Varies with device,0.0,High,1,0
3904,whatsapp messenger,COMMUNICATION,4.4,69109672,Varies with device,1.000000e+09,Free,0.0,Everyone,Communication,2018-08-03,Varies with device,Varies with device,0.0,High,1,0
2604,instagram,SOCIAL,4.5,66577446,Varies with device,1.000000e+09,Free,0.0,Teen,Social,2018-07-31,Varies with device,Varies with device,0.0,High,1,0
2545,instagram,SOCIAL,4.5,66577313,Varies with device,1.000000e+09,Free,0.0,Teen,Social,2018-07-31,Varies with device,Varies with device,0.0,High,1,0
3909,instagram,SOCIAL,4.5,66509917,Varies with device,1.000000e+09,Free,0.0,Teen,Social,2018-07-31,Varies with device,Varies with device,0.0,High,1,0
382,messenger – text and video chat for free,COMMUNICATION,4.0,56646578,Varies with device,1.000000e+09,Free,0.0,Everyone,Communication,2018-08-01,Varies with device,Varies with device,0.0,Medium,1,0
335,messenger – text and video chat for free,COMMUNICATION,4.0,56642847,Varies with device,1.000000e+09,Free,0.0,Everyone,Communication,2018-08-01,Varies with device,Varies with device,0.0,Medium,1,0
1879,clash of clans,GAME,4.6,44893888,98M,1.000000e+08,Free,0.0,Everyone 10+,Strategy,2018-07-15,10.322.16,4.1 and up,0.0,High,1,0

30. Bottom 10 apps based on installs

In [35]:
df.nsmallest(10, "Installs")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install,Type_Numeric
2454,kba-ez health guide,MEDICAL,5.0,4,25M,1.0,Free,0.00,Everyone,Medical,2018-08-02,1.0.72,4.0.3 and up,0.00,High,0,0
5917,ra ga ba,GAME,5.0,2,20M,1.0,Paid,1.49,Everyone,Arcade,2017-02-08,1.0.4,2.3 and up,1.49,High,0,1
10697,mu.f.o.,GAME,5.0,2,16M,1.0,Paid,0.99,Everyone,Arcade,2017-03-03,1.0,2.3 and up,0.99,High,0,1
2450,tablet reminder,MEDICAL,5.0,4,2.5M,5.0,Free,0.00,Everyone,Medical,2018-08-03,1.0,4.1 and up,0.00,High,0,0
2459,anatomy & physiology vocabulary exam review app,MEDICAL,5.0,1,4.6M,5.0,Free,0.00,Everyone,Medical,2018-08-02,2.0,4.0 and up,0.00,High,0,0
2484,clinic doctor ehr,MEDICAL,5.0,2,7.1M,5.0,Free,0.00,Everyone,Medical,2018-08-03,1.0.51.0.3,8.0 and up,0.00,High,0,0
6700,brick breaker br,GAME,5.0,7,19M,5.0,Free,0.00,Everyone,Arcade,2018-07-23,1.0,4.1 and up,0.00,High,0,0
7147,cb heroes,SOCIAL,5.0,5,1.8M,5.0,Free,0.00,Everyone,Social,2018-08-04,1.2.4,5.0 and up,0.00,High,0,0
7731,cq espm,BUSINESS,5.0,2,3.4M,5.0,Free,0.00,Everyone,Business,2017-06-03,1.0.1,4.1 and up,0.00,High,0,0
8146,cz-help,BOOKS AND REFERENCE,5.0,2,1.4M,5.0,Free,0.00,Everyone,Books & Reference,2018-07-13,0.1,4.4 and up,0.00,High,0,0

31. Rank apps based on Rating

In [36]:
df["Rating_Rank"] = df["Rating"].rank(
    ascending=False
)

df[["App", "Rating", "Rating_Rank"]]

                                                     App  Rating  Rating_Rank
0         photo editor & candy camera & grid & scrapbook     4.1       6080.0
1                                    coloring book moana     3.9       7133.5
2      u launcher lite – free live cool themes, hide ...     4.7        828.5
3                                  sketch - draw & paint     4.5       2327.0
4                  pixel draw - number art coloring book     4.3       4355.5
...                                                  ...     ...          ...
10834                                      fr calculator     4.0       6678.0
10836                                   sya9a maroc - fr     4.5       2327.0
10837                   fr. mike schmitz audio teachings     5.0        136.0
10839                      the scp foundation db fr nn5n     4.5       2327.0
10840      ihoroscope - 2018 daily horoscope & astrology     4.5       2327.0

[8892 rows x 3 columns]

32. Average Rating for each Category

In [37]:
df.groupby("Category")["Rating"].mean()

Category
ART AND DESIGN         4.358065
AUTO AND VEHICLES      4.190411
BEAUTY                 4.278571
BOOKS AND REFERENCE    4.347458
BUSINESS               4.102593
COMICS                 4.155172
COMMUNICATION          4.151466
DATING                 3.971698
EDUCATION              4.375969
ENTERTAINMENT          4.136036
EVENTS                 4.435556
FAMILY                 4.191153
FINANCE                4.127445
FOOD AND DRINK         4.164151
GAME                   4.281285
HEALTH AND FITNESS     4.261450
HOUSE AND HOME         4.164706
LIBRARIES AND DEMO     4.178462
LIFESTYLE              4.096066
MAPS AND NAVIGATION    4.051613
MEDICAL                4.182450
NEWS AND MAGAZINES     4.128505
PARENTING              4.300000
PERSONALIZATION        4.333871
PHOTOGRAPHY            4.182895
PRODUCTIVITY           4.201796
SHOPPING               4.251485
SOCIAL                 4.254918
SPORTS                 4.225175
TOOLS                  4.047411
TRAVEL AND LOCAL       4.094146
VIDEO PLAYERS          4.063750
WEATHER                4.244000
Name: Rating, dtype: float64

33. Total installs for each Category

In [38]:
df.groupby("Category")["Installs"].sum()

Category
ART AND DESIGN         1.242331e+08
AUTO AND VEHICLES      5.312980e+07
BEAUTY                 2.691620e+07
BOOKS AND REFERENCE    1.916292e+09
BUSINESS               8.635181e+08
COMICS                 5.603610e+07
COMMUNICATION          2.415224e+10
DATING                 2.065224e+08
EDUCATION              5.338520e+08
ENTERTAINMENT          2.455660e+09
EVENTS                 1.594941e+07
FAMILY                 1.004113e+10
FINANCE                7.703124e+08
FOOD AND DRINK         2.577778e+08
GAME                   3.154386e+10
HEALTH AND FITNESS     1.361006e+09
HOUSE AND HOME         1.250820e+08
LIBRARIES AND DEMO     6.208300e+07
LIFESTYLE              5.347411e+08
MAPS AND NAVIGATION    7.242676e+08
MEDICAL                4.216268e+07
NEWS AND MAGAZINES     5.393111e+09
PARENTING              3.111611e+07
PERSONALIZATION        2.074353e+09
PHOTOGRAPHY            9.721243e+09
PRODUCTIVITY           1.246307e+10
SHOPPING               2.573332e+09
SOCIAL                 1.251384e+10
SPORTS                 1.528531e+09
TOOLS                  1.145072e+10
TRAVEL AND LOCAL       6.361859e+09
VIDEO PLAYERS          6.221897e+09
WEATHER                4.260965e+08
Name: Installs, dtype: float64

34. Count number of apps in each Category

In [39]:
df["Category"].value_counts()

Category
FAMILY                 1718
GAME                   1074
TOOLS                   734
PRODUCTIVITY            334
FINANCE                 317
PERSONALIZATION         310
COMMUNICATION           307
LIFESTYLE               305
PHOTOGRAPHY             304
MEDICAL                 302
SPORTS                  286
BUSINESS                270
HEALTH AND FITNESS      262
SOCIAL                  244
NEWS AND MAGAZINES      214
TRAVEL AND LOCAL        205
SHOPPING                202
BOOKS AND REFERENCE     177
VIDEO PLAYERS           160
DATING                  159
EDUCATION               129
MAPS AND NAVIGATION     124
ENTERTAINMENT           111
FOOD AND DRINK          106
WEATHER                  75
AUTO AND VEHICLES        73
HOUSE AND HOME           68
LIBRARIES AND DEMO       65
ART AND DESIGN           62
COMICS                   58
PARENTING                50
EVENTS                   45
BEAUTY                   42
Name: count, dtype: int64

35. Multiple aggregations per Category

In [40]:
df.groupby("Category").agg(
    {
        "Rating": "mean",
        "Installs": "max"
    }
)

                       Rating      Installs
Category
ART AND DESIGN       4.358065  5.000000e+07
AUTO AND VEHICLES    4.190411  1.000000e+07
BEAUTY               4.278571  1.000000e+07
BOOKS AND REFERENCE  4.347458  1.000000e+09
BUSINESS             4.102593  1.000000e+08
COMICS               4.155172  1.000000e+07
COMMUNICATION        4.151466  1.000000e+09
DATING               3.971698  1.000000e+07
EDUCATION            4.375969  1.000000e+08
ENTERTAINMENT        4.136036  1.000000e+09
EVENTS               4.435556  5.000000e+06
FAMILY               4.191153  1.000000e+09
FINANCE              4.127445  1.000000e+08
FOOD AND DRINK       4.164151  1.000000e+07
GAME                 4.281285  1.000000e+09
HEALTH AND FITNESS   4.261450  5.000000e+08
HOUSE AND HOME       4.164706  1.000000e+07
LIBRARIES AND DEMO   4.178462  1.000000e+07
LIFESTYLE            4.096066  1.000000e+08
MAPS AND NAVIGATION  4.051613  1.000000e+08
MEDICAL              4.182450  5.000000e+06
NEWS AND MAGAZINES   4.128505  1.000000e+09
PARENTING            4.300000  1.000000e+07
PERSONALIZATION      4.333871  1.000000e+08
PHOTOGRAPHY          4.182895  1.000000e+09
PRODUCTIVITY         4.201796  1.000000e+09
SHOPPING             4.251485  1.000000e+08
SOCIAL               4.254918  1.000000e+09
SPORTS               4.225175  1.000000e+08
TOOLS                4.047411  1.000000e+09
TRAVEL AND LOCAL     4.094146  1.000000e+09
VIDEO PLAYERS        4.063750  1.000000e+09
WEATHER              4.244000  5.000000e+07

36. Split dataset into multiple tables

In [41]:
apps_info = df[
    ["App", "Category", "Rating"]
]

installs_info = df[
    ["App", "Installs", "Reviews"]
]

pricing_info = df[
    ["App", "Type", "Price"]
]

In [42]:
apps_info.head()

                                                 App        Category  Rating
0     photo editor & candy camera & grid & scrapbook  ART AND DESIGN     4.1
1                                coloring book moana  ART AND DESIGN     3.9
2  u launcher lite – free live cool themes, hide ...  ART AND DESIGN     4.7
3                              sketch - draw & paint  ART AND DESIGN     4.5
4              pixel draw - number art coloring book  ART AND DESIGN     4.3

In [43]:
installs_info.head()

                                                 App    Installs  Reviews
0     photo editor & candy camera & grid & scrapbook     10000.0      159
1                                coloring book moana    500000.0      967
2  u launcher lite – free live cool themes, hide ...   5000000.0    87510
3                              sketch - draw & paint  50000000.0   215644
4              pixel draw - number art coloring book    100000.0      967

In [44]:
pricing_info.head()

                                                 App  Type  Price
0     photo editor & candy camera & grid & scrapbook  Free    0.0
1                                coloring book moana  Free    0.0
2  u launcher lite – free live cool themes, hide ...  Free    0.0
3                              sketch - draw & paint  Free    0.0
4              pixel draw - number art coloring book  Free    0.0

37. Merge app details with installs data

In [45]:
merged_df = pd.merge(
    apps_info,
    installs_info,
    on="App"
)

merged_df.head()

,App,Category,Rating,Installs,Reviews
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,10000.0,159
1,coloring book moana,ART AND DESIGN,3.9,500000.0,967
2,coloring book moana,ART AND DESIGN,3.9,500000.0,974
3,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,5000000.0,87510
4,sketch - draw & paint,ART AND DESIGN,4.5,50000000.0,215644

38. Perform an INNER JOIN

In [46]:
inner_join = pd.merge(
    apps_info,
    installs_info,
    on="App",
    how="inner"
)

inner_join.head()

,App,Category,Rating,Installs,Reviews
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,10000.0,159
1,coloring book moana,ART AND DESIGN,3.9,500000.0,967
2,coloring book moana,ART AND DESIGN,3.9,500000.0,974
3,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,5000000.0,87510
4,sketch - draw & paint,ART AND DESIGN,4.5,50000000.0,215644

39. Perform LEFT JOIN and find missing values

In [47]:
left_join = pd.merge(
    apps_info,
    pricing_info,
    on="App",
    how="left"
)

left_join.head()

,App,Category,Rating,Type,Price
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,Free,0.0
1,coloring book moana,ART AND DESIGN,3.9,Free,0.0
2,coloring book moana,ART AND DESIGN,3.9,Free,0.0
3,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,Free,0.0
4,sketch - draw & paint,ART AND DESIGN,4.5,Free,0.0

40. Combine two DataFrames vertically

In [51]:
df1 = df.iloc[:100]
df2 = df.iloc[100:200]

In [52]:
combined_df = pd.concat(
    [df1, df2],
    ignore_index=True
)

combined_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install,Type_Numeric,Rating_Rank
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,0.0,High,0,0,6080.0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,0.0,Medium,0,0,7133.5
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,0.0,High,1,0,828.5
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,0.0,High,1,0,2327.0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,0.0,High,0,0,4355.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,polaris office for lg,BUSINESS,4.2,30847,55M,5000000.0,Free,0.0,Everyone,Business,2018-02-08,7.3.21,4.1 and up,0.0,High,1,0,5307.5
196,call blocker,BUSINESS,4.6,188841,3.2M,5000000.0,Free,0.0,Everyone,Business,2018-06-21,1.1.13,4.0 and up,0.0,High,1,0,1454.5
197,jobs in alabama - jobs in alba,BUSINESS,4.1,11622,Varies with device,5000000.0,Free,0.0,Everyone,Business,2018-07-26,Varies with device,Varies with device,0.0,High,1,0,6080.0
198,square point of sale - pos,BUSINESS,4.6,95912,Varies with device,5000000.0,Free,0.0,Everyone,Business,2018-07-30,Varies with device,Varies with device,0.0,High,1,0,1454.5
199,plugin:aot v5.0,BUSINESS,3.1,4034,23k,100000.0,Free,0.0,Everyone,Business,2015-09-11,3.0.1.11 (Build 311),2.2 and up,0.0,Medium,0,0,8496.0

In [53]:
pd.concat([df1, df2], ignore_index=True)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Revenue,Rating_Group,High_Install,Type_Numeric,Rating_Rank
0,photo editor & candy camera & grid & scrapbook,ART AND DESIGN,4.1,159,19M,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,0.0,High,0,0,6080.0
1,coloring book moana,ART AND DESIGN,3.9,967,14M,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,0.0,Medium,0,0,7133.5
2,"u launcher lite – free live cool themes, hide ...",ART AND DESIGN,4.7,87510,8.7M,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,0.0,High,1,0,828.5
3,sketch - draw & paint,ART AND DESIGN,4.5,215644,25M,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,0.0,High,1,0,2327.0
4,pixel draw - number art coloring book,ART AND DESIGN,4.3,967,2.8M,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,0.0,High,0,0,4355.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,polaris office for lg,BUSINESS,4.2,30847,55M,5000000.0,Free,0.0,Everyone,Business,2018-02-08,7.3.21,4.1 and up,0.0,High,1,0,5307.5
196,call blocker,BUSINESS,4.6,188841,3.2M,5000000.0,Free,0.0,Everyone,Business,2018-06-21,1.1.13,4.0 and up,0.0,High,1,0,1454.5
197,jobs in alabama - jobs in alba,BUSINESS,4.1,11622,Varies with device,5000000.0,Free,0.0,Everyone,Business,2018-07-26,Varies with device,Varies with device,0.0,High,1,0,6080.0
198,square point of sale - pos,BUSINESS,4.6,95912,Varies with device,5000000.0,Free,0.0,Everyone,Business,2018-07-30,Varies with device,Varies with device,0.0,High,1,0,1454.5
199,plugin:aot v5.0,BUSINESS,3.1,4034,23k,100000.0,Free,0.0,Everyone,Business,2015-09-11,3.0.1.11 (Build 311),2.2 and up,0.0,Medium,0,0,8496.0

In [1]:
df.to_excel("google_playstore_cleaned.xlsx", index=False)

NameError: name 'df' is not defined